#!/bin/bash

echo "Please enter your API key:"
read -r -s ans
echo "#!/bin/bash" > secrets.env
echo "export WATERSHED_API_KEY=\"$ans\"" >> secrets.env
echo "Successfully stored API key in secrets.env"

source secrets.env
poetry run python upload_dataset.py
